#' Read and Process APAC Records
#'
#' This function reads the APAC database, combining the AQ and AR bases if present, selects variables of interest,
#' creates variables for year of service and diagnosis, exports the frequency table of procedures by ICD, and performs
#' a consistency diagnostic of the variables for subsequent analyses.
#'
#' @importFrom magrittr %>%
#' @param read_bases Character. Indicates which APAC bases will be extracted and analyzed. Options: `'AQ'`, `'AR'`, or both.
#' @param aq_file Character (optional). A string with the name of the AQ base file to be read.
#' @param ar_file Character (optional). A string with the name of the AR base file to be read.
#' @param dir Character. Directory containing .csv files of AQ/AR bases. If `NULL`, defaults to `'datasus_files'` in the current directory.
#' @param first_year Numeric (optional). The oldest year for the database. See **Details**.
#' @param last_year Numeric (optional). The most recent year for the database. See **Details**.
#' @param file_code Character (optional). A string used in naming output files generated by `get_datasus()` or `merge_datasus()`. Defaults to `'APAC'`.
#' @param procedures_filename Character (optional). Customizes the name of the file with the procedure table.
#' @param run_diagnostics Logical. If `TRUE`, performs diagnostic analysis. Default is `TRUE`.
#' @param select_variables Character (optional). Additional variables from the original APAC tables to retain in the processed table.
#' @param clear_cache Logical. If `TRUE`, frees RAM space during processing with `gc()`. Default is `TRUE`.
#' @param silent Logical. If `TRUE`, suppresses console messages. Default is `FALSE`.
#' @param export_procedure_table Logical. If `TRUE`, saves the frequency table of procedures described in APAC. Default is `FALSE`.
#' @param selected_med_procedures Character vector of SIGPTAP procedure codes to include in the analysis.
#' @param med_proced_to_remove Character vector of SIGPTAP procedure codes to exclude from the analysis.
#' @param group_icd Logical. If `TRUE`, groups procedures by ICD.
#' @param icd_group_file_path Character (optional). Path and name of the ICD grouping file. Must include columns `'icd'` and `'icd_group'`.
#' @details
#' The `first_year` and `last_year` parameters define the time range for reading the AQ/AR base file unless otherwise specified.
#' These parameters are also part of the output procedure table's name.
#'
#' The function identifies potential inconsistencies, including missing values, date formatting errors, and mismatched age or diagnostic codes.
#' @return
#' - If `run_diagnostics = TRUE`: Returns a list with:
#'   * `APAC`: The processed APAC table.
#'   * `diag_list`: A list of diagnostic tables, including errors and summaries.
#' - If `run_diagnostics = FALSE`: Returns the processed APAC table.
#' @export
#' @examples
#' \dontrun{
#' # Read and process APAC data for AQ and AR bases, grouping by ICD
#' apac_data <- read_apac(
#'   read_bases = c('AQ', 'AR'),
#'   aq_file = 'aq_2010_2020_full.csv',
#'   ar_file = 'ar_2010_2020_full.csv',
#'   dir = 'datasus_files/',
#'   first_year = 2010,
#'   last_year = 2020,
#'   file_code = 'default',
#'   run_diagnostics = TRUE,
#'   export_procedure_table = TRUE,
#'   selected_med_procedures = c('0304040029','0304040045'),
#'   med_proced_to_remove = c('0304040070','0304040088'),
#'   group_icd = TRUE,
#'   icd_group_file_path = 'source_files/icd_group_cancer.csv'
#' )
#' head(apac_data$APAC)
#' }
read_apac <- function(read_bases = c("AQ", "AR"),
                      aq_file = NA,
                      ar_file = NA,
                      dir = NULL,
                      first_year = NA,
                      last_year = NA,
                      file_code = NA,
                      procedures_filename = NA,
                      run_diagnostics = TRUE,
                      select_variables = NA,
                      clear_cache = TRUE,
                      silent = FALSE,
                      export_procedure_table = FALSE,
                      selected_med_procedures,
                      med_proced_to_remove,
                      group_icd = FALSE,
                      icd_group_file_path = NULL) {
  sigtap_procedures <- OncoDatasusR::sigtap_procedures
  icd_description <- OncoDatasusR::icd_description

  if (!missing(select_variables)) {
    if (any(
      select_variables %in% c(
        "AP_CNSPCN_ENC64",
        "AP_CNSPCN_ENC64",
        "AQ_DTIDEN",
        "AR_DTIDEN",
        "AP_CMP",
        "AP_SEXO",
        "AP_NUIDADE",
        "AP_COIDADE",
        "AP_CEPPCN",
        "AP_CIDPRI",
        "AP_PRIPAL",
        "AQ_ESTADI",
        "AR_ESTADI",
        "AP_MUNPCN"
      )
    ))
    stop(
      "Error: The variables 'AP_CNSPCN_ENC64', 'AP_CNSPCN_ENC64', 'AQ_DTIDEN', 'AR_DTIDEN', 'AP_CMP', 'AP_SEXO', 'AP_NUIDADE', 'AP_COIDADE', 'AP_CEPPCN', 'AP_CIDPRI', 'AP_PRIPAL', 'AQ_ESTADI', 'AR_ESTADI' and 'AP_MUNPCN' are reserved and cannot be selected."
    )
  }

  if (is.null(dir)) {
    dir <- paste0(getwd(), "/datasus_files/")
    if (!dir.exists(dir)) {
      stop("Error: The folder 'datasus_files' was not found in the current working directory.")
    }
  } else {
    if (!dir.exists(dir)) {
      stop("Error: The directory does not exist.")
    }
  }

  if (group_icd) {
    if (file.exists(icd_group_file_path)) {
      icd_groups <- read.csv(
        icd_group_file_path,
        colClasses = c("character", "character"),
        encoding = "UTF-8"
      )
    } else {
      stop("Error: File with ICD grouping not found!")
    }
  }

  if (group_icd) {
    if (all(c("icd_group", "icd") %in%
            colnames(icd_groups))) {
      icd_groups <- icd_groups %>%
        dplyr::select(icd, icd_group)
    } else {
      stop("Error: The ICD grouping file must contain the columns 'icd' and 'icd_group'")
    }
  }

  if ("AQ" %in% read_bases)
    aq_file_name <- paste0(dir, "aq_", file_code, "_", first_year, last_year, "_full.csv")
  if ("AR" %in% read_bases)
    ar_file_name <- paste0(dir, "ar_", file_code, "_", first_year, last_year, "_full.csv")

  if (!is.na(aq_file))
    aq_file_name <- paste0(dir, aq_file)
  if (!is.na(ar_file))
    ar_file_name <- paste0(dir, ar_file)

  if ("AQ" %in% read_bases) {
    if (file.exists(aq_file_name)) {
      if (!silent)
        message(paste0("Reading: ", aq_file_name))
      aq_df <- data.frame(data.table::fread(aq_file_name, colClasses = "character"))
    } else {
      stop(paste0("File ", aq_file_name, " not found!"))
    }
  }

  if ("AR" %in% read_bases) {
    if (file.exists(ar_file_name)) {
      if (!silent)
        message(paste0("Reading: ", ar_file_name))
      ar_df <- data.frame(data.table::fread(ar_file_name, colClasses = "character"))
    } else {
      stop(paste0("File ", ar_file_name, " not found!"))
    }
  }

  # Part 1: Unify the AQ and AR bases

  # Rename and mutate the columns of the AQ and AR bases to
  # facilitate the union of the tables
  if ("AQ" %in% read_bases) {
    aq_df_new <- aq_df %>%
      dplyr::rename(
        cod_paciente = AP_CNSPCN_ENC64,
        data_diagnostico = AQ_DTIDEN,
        data_atendimento = AP_CMP,
        sexo = AP_SEXO,
        idade = AP_NUIDADE,
        cod_idade = AP_COIDADE,
        cep_paciente = AP_CEPPCN,
        CID_completo = AP_CIDPRI,
        proc = AP_PRIPAL,
        estadi = AQ_ESTADI,
        ap_munpcn = AP_MUNPCN
      ) %>%
      dplyr::mutate(
        ano_diagnostico = substr(data_diagnostico, 1, 4),
        ano_atendimento = substr(data_atendimento, 1, 4),
        Base = "AQ",
        cid_prim = substr(CID_completo, 1, 3)
      )
  }

  if ("AR" %in% read_bases) {
    ar_df_new <- ar_df %>%
      dplyr::rename(
        cod_paciente = AP_CNSPCN_ENC64,
        data_diagnostico = AR_DTIDEN,
        data_atendimento = AP_CMP,
        sexo = AP_SEXO,
        idade = AP_NUIDADE,
        cod_idade = AP_COIDADE,
        cep_paciente = AP_CEPPCN,
        CID_completo = AP_CIDPRI,
        proc = AP_PRIPAL,
        estadi = AR_ESTADI,
        ap_munpcn = AP_MUNPCN
      ) %>%
      dplyr::mutate(
        ano_diagnostico = substr(data_diagnostico, 1, 4),
        ano_atendimento = substr(data_atendimento, 1, 4),
        Base = "AR",
        cid_prim = substr(CID_completo, 1, 3)
      )
  }

  if ("AQ" %in% read_bases & "AR" %in% read_bases) {
    APAC <- dplyr::bind_rows(aq_df_new, ar_df_new)
  } else if ("AQ" %in% read_bases) {
    APAC <- aq_df_new
  } else if ("AR" %in% read_bases) {
    APAC <- ar_df_new
  }

  most_recent_date <- APAC %>%
    dplyr::summarise(maxdate = max(AP_MVM)) %>%
    dplyr::mutate(maxdate = paste0(maxdate, "01")) %>%
    dplyr::mutate(maxdate = as.Date(maxdate, format = "%Y%m%d")) %>%
    dplyr::mutate(maxdate = lubridate::ceiling_date(maxdate, unit = "month"))

  variables <- c(
    "Base",
    "cod_paciente",
    "cid_prim",
    "CID_completo",
    "proc",
    "data_diagnostico",
    "ano_diagnostico",
    "data_atendimento",
    "ano_atendimento",
    "cep_paciente",
    "sexo",
    "idade",
    "cod_idade",
    "estadi",
    "ap_munpcn"
  )

  if (!missing(select_variables))
    variables <- c(variables, select_variables)

  APAC <- APAC %>%
    dplyr::select(tidyr::all_of(variables))

  if (clear_cache) {
    if ("AQ" %in% read_bases)
      rm(aq_df, aq_df_new)
    if ("AR" %in% read_bases)
      rm(ar_df, ar_df_new)
    gc()
  }

  APAC[APAC == ""] <- NA

  record_n_1 <- nrow(APAC)
  patient_n_1 <- length(unique(APAC$cod_paciente))
  NA_procedures_n <- sum(is.na(APAC$proc))
  APAC <- APAC %>%
    tidyr::drop_na(proc)
  if (!missing(med_proced_to_remove))
    APAC <- APAC %>%
    dplyr::filter(!(proc %in% med_proced_to_remove))
  if (!missing(selected_med_procedures))
    APAC <- APAC %>%
    dplyr::filter(proc %in% selected_med_procedures)
  record_n_2 <- nrow(APAC)
  patient_n_2 <- length(unique(APAC$cod_paciente))

  if (run_diagnostics) {
    suppressWarnings({
      diag_list <- list()

      proc_diag_table <- data.frame(
        before = c(record_n_1, patient_n_1, NA_procedures_n),
        after = c(record_n_2, patient_n_2, 0)
      ) %>%
        dplyr::mutate(dif = after - before)

      rownames(proc_diag_table) = c("Rows", "Unique patients", "NA values")

      diag_list$proc_diag_table <- proc_diag_table

      # Save table including the number of ICD records by
      # base
      ICD_base_table <- APAC %>%
        dplyr::count(Base, cid_prim) %>%
        tidyr::pivot_wider(names_from = "cid_prim", values_from = "n")  #

      ICD_base_table_total <- APAC %>%
        dplyr::count(cid_prim) %>%
        tidyr::pivot_wider(names_from = "cid_prim", values_from = "n") %>%
        dplyr::mutate(Base = "Total")

      ICD_base_table <- dplyr::bind_rows(ICD_base_table, ICD_base_table_total) %>%
        janitor::adorn_totals(c("col"))

      diag_list$ICD_base_table <- ICD_base_table

      # Save table with the number of patients by base
      # (assuming that each patient code is equal to a
      # unique patient)
      unique_patient_code_table <- APAC %>%
        dplyr::group_by(Base) %>%
        dplyr::summarise(unique_patient_code = dplyr::n_distinct(cod_paciente))

      unique_patient_code_total <- APAC %>%
        dplyr::summarise(unique_patient_code = dplyr::n_distinct(cod_paciente)) %>%
        dplyr::mutate(Base = "Total")

      unique_patient_code_table <- dplyr::bind_rows(unique_patient_code_table, unique_patient_code_total)

      diag_list$unique_patient_code_all <- unique_patient_code_table

      # Count the number of missing or incongruent values
      NA_column <- APAC %>%
        dplyr::select(
          -CID_completo,
          -Base,
          -cid_prim,
          -cod_paciente,
          -ano_diagnostico,-ano_atendimento
        ) %>%
        dplyr::summarise_all( ~ (sum(is.na(.))))

      variable_names <- names(
        APAC %>%
          dplyr::select(
            -Base,
            -cid_prim,
            -CID_completo,
            -cod_paciente,
            -ano_diagnostico,-ano_atendimento
          )
      )

      error_table <- data.frame(matrix(NA, 4, ncol(APAC) -
                                         6))
      names(error_table) <- variable_names
      rownames(error_table) <- c("value_error",
                                 "date_error",
                                 "date_below_98",
                                 "future_date")

      if ("proc" %in% variable_names)
        error_table$proc[1] <- sum(nchar(APAC$proc) !=
                                     10 | is.na(as.numeric(APAC$proc)))
      if ("data_diagnostico" %in% variable_names) {
        diagnotic_date <- as.Date(APAC$data_diagnostico, format = "%Y%m%d")
        error_table$data_diagnostico[1] <- sum(nchar(APAC$data_diagnostico) !=
                                                 8 | is.na(as.numeric(APAC$data_diagnostico)))
        error_table$data_diagnostico[2] <- sum(is.na(as.Date(APAC$data_diagnostico, format = "%Y%m%d")))
        error_table$data_diagnostico[3] <- sum(diagnotic_date <= as.Date("1998-01-01"))
        error_table$data_diagnostico[4] <- sum(diagnotic_date >= most_recent_date$maxdate)
      }

      if ("data_atendimento" %in% variable_names) {
        service_date <- as.Date(paste0(APAC$data_atendimento, "01"), format = "%Y%m%d")
        error_table$data_atendimento[1] <- sum(nchar(APAC$data_atendimento) !=
                                                 6 | is.na(as.numeric(APAC$data_atendimento)))
        error_table$data_atendimento[2] <- sum(is.na(as.Date(
          paste0(APAC$data_atendimento, "01"), format = "%Y%m%d"
        )))
        error_table$data_atendimento[3] <- sum(service_date <= as.Date("1998-01-01"))
        error_table$data_atendimento[4] <- sum(service_date >= most_recent_date$maxdate)
      }

      if ("cep_paciente" %in% variable_names)
        error_table$cep_paciente[1] <- sum(nchar(APAC$cep_paciente) !=
                                             8 | is.na(as.numeric(APAC$cep_paciente)))
      if ("sexo" %in% variable_names)
        error_table$sexo[1] <- sum(!(APAC$sexo %in% c("F", "M")))
      if ("idade" %in% variable_names) {
        # Count possible values outside the interval
        # between 0 and 99
        age_interval_error_n <- APAC %>%
          dplyr::select(idade) %>%
          dplyr::mutate(idade = as.numeric(idade)) %>%
          dplyr::filter(idade < 0 | idade > 99) %>%
          nrow()
        # Count possible non-numeric values
        age_non_numeric <- sum(is.na(as.numeric(APAC$idade)))
        # Sum the both counts
        error_table$idade[1] <- age_interval_error_n + age_interval_error_n
      }

      if ("cod_idade" %in% variable_names) {
        # Count possible values outside the list of
        # possible codes
        age_code_interval_error_n <- APAC %>%
          dplyr::select(cod_idade) %>%
          dplyr::mutate(cod_idade = as.numeric(cod_idade)) %>%
          dplyr::filter(cod_idade < 0 | cod_idade > 5) %>%
          nrow()
        # Count the possible non-numeric values
        age_code_non_numeric <- sum(is.na(as.numeric(APAC$cod_idade)))
        # Sum the both counts
        error_table$cod_idade[1] <- age_code_interval_error_n +
          age_code_non_numeric
      }

      error_proportion <- format(round((
        colSums(error_table, na.rm = TRUE) +
          NA_column
      ) / nrow(APAC) *
        100, 2), nsmall = 2)

      error_table_all <- rbind(
        missing_values = NA_column,
        error_table,
        total = colSums(error_table, na.rm = TRUE) +
          NA_column,
        proportion = error_proportion
      )

      error_table_all[is.na(error_table_all)] <- " "

      diag_list$error_table_all <- error_table_all

      # Creaate a table with the count of diagnostic and
      # attendance years
      diagnostic_year_table <- APAC %>%
        dplyr::count(ano_diagnostico) %>%
        dplyr::arrange(ano_diagnostico) %>%
        dplyr::rename(ano = ano_diagnostico) %>%
        dplyr::rename(ano_diagnostico_registros = n)
      service_year_table <- APAC %>%
        dplyr::count(ano_atendimento) %>%
        dplyr::arrange(ano_atendimento) %>%
        dplyr::rename(ano = ano_atendimento) %>%
        dplyr::rename(ano_atendimento_registros = n)
      diag_list$dates_year_table <- diagnostic_year_table %>%
        dplyr::left_join(service_year_table, by = "ano")

      # Create a table with the count of ICD codes
      icd_ds_tbl <- APAC %>%
        dplyr::count(CID_completo) %>%
        dplyr::arrange(CID_completo) %>%
        dplyr::left_join(icd_description, by = c(CID_completo = "cd_cid")) %>%
        dplyr::relocate(CID_completo, ds_cid) %>%
        dplyr::mutate(CID_completo = ifelse(
          nchar(CID_completo) >
            3,
          paste0(
            substr(CID_completo, 1, 3),
            ".",
            substr(CID_completo, 4, 4)
          ),
          CID_completo
        )) %>%
        dplyr::mutate(CID_completo = ifelse(
          nchar(CID_completo) ==
            3,
          paste0(CID_completo, ".x"),
          CID_completo
        )) %>%
        dplyr::mutate(CID_principal = substr(CID_completo, 1, 3)) %>%
        dplyr::relocate(CID_principal)

      main_cid_total_tbl <- icd_ds_tbl %>%
        dplyr::group_by(CID_principal) %>%
        dplyr::summarise(total = sum(n))

      icd_ds_tbl <- icd_ds_tbl %>%
        dplyr::left_join(main_cid_total_tbl, by = c("CID_principal")) %>%
        dplyr::mutate(CID_principal = paste0(CID_principal, " (Total = ", total, ")")) %>%
        dplyr::select(-total)

      diag_list$icd_ds_tbl <- icd_ds_tbl
    })
  }

  # Create a table with the count of procedures
  if (group_icd) {
    APAC <- APAC %>%
      dplyr::left_join(icd_groups, by = c(cid_prim = "icd"))

    procedure_table <- APAC %>%
      dplyr::count(proc, icd_group) %>%
      dplyr::arrange(desc(n)) %>%
      tidyr::pivot_wider(names_from = icd_group, values_from = n)

  } else {
    procedure_table <- APAC %>%
      dplyr::count(proc, cid_prim) %>%
      dplyr::arrange(cid_prim, desc(n)) %>%
      tidyr::pivot_wider(names_from = cid_prim, values_from = n)
  }

  # Reorganize the table according to the number of CID codes
  if (length(unique(APAC$cid_prim)) >
      1) {
    procedure_table_all <- APAC %>%
      dplyr::count(proc) %>%
      dplyr::rename(Total = n)

    procedure_table <- procedure_table %>%
      dplyr::left_join(procedure_table_all, by = "proc")
  }

  # Includes the description of the procedures
  procedure_table <- procedure_table %>%
    dplyr::left_join(sigtap_procedures, by = c(proc = "key")) %>%
    dplyr::relocate(proc, description) %>%
    dplyr::rename(procedure_code = proc) %>%
    data.frame()

  if (run_diagnostics)
    diag_list$procedure_table <- procedure_table

  if (export_procedure_table) {
    if (!is.na(procedures_filename)) {
      filename = procedures_filename
    } else {
      if (is.na(file_code))
        file_code <- "APAC"
      filename = paste0(file_code,
                        "_",
                        first_year,
                        "_",
                        last_year,
                        "_procedures.csv")
    }
    if (!silent)
      message(paste0("Writing: ", paste0(dir, filename)))
    readr::write_csv(procedure_table, file = paste0(dir, filename))
  }
  if (run_diagnostics) {
    output <- list(APAC = APAC, diag_list = diag_list)
  } else {
    output <- APAC
  }
  return(output)
}
